### ISSUE TITLE
Checkpoint 1 requirements are done

### ISSUE THREAD

**Issue by fchristian1992** [fchristian1992/pcHardwareViewer#1]
@pawaitemadisoncollege

**Comment by pawaitemadisoncollege** [comment]
Hi @fchristian1992! It looks like you are off to a solid start and have a very good idea of what you'll be building!  Here are my findings while reviewing your project for checkpoint 1:

**problem statement**

Straightforward and clear!

**user stories**

- [ ] add and edit of parts would be two separate stories
- [ ] deleting is a requirement of the project, is there a place you can add in a meaningful story that includes a delete scenario?
- [ ] to address the one-to-many aspect of the project, would it make sense to have a story related to a user have more than one pc? Add, edit, delete pcs?

**project plan**
 
- [ ] What do you think about adding the tasks you will need to meet Checkpoint 2 and 3? 
- [ ] I see reference to specific jsps. You might also consider adding the various user stories - when do you hope to start and finish each one? 

**screen design**

A very good start! 
- [ ]  AWS Cognito, which we will practice with next week, provides us with sign up and sign in screens so you may not need to actually build those out.
- [ ] With the part add/edit, will you create a separate screen for each PC Part, or will that be built dynamically depending on the part the user is currently adding or editing? 

 **reflection statements/time log/journal** 

- [ ] Be sure to keep these up-to-date - we are now in week 6.
- [ ] This appears to be incomplete: https://github.com/fchristian1992/pcHardwareViewer/blob/main/timeLog.md. If you would like to include the time spent here: https://github.com/fchristian1992/pcHardwareViewer/blob/main/WeeklyReflection.md, then you could remove the timeLog.md. I don't want you to have to enter this type of information in two places unless you find it valuable to do so.

**Web Service or API**.  Have you thought about what you might include for this requirement?
